---
all:
  hosts:
    wendelstein:
      ansible_host: wendelstein.jaseg.net
      ansible_ssh_identity_file: ~/.ssh/id_ed25519
      ansible_user: root
      ansible_python_interpreter: /usr/bin/python3
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ansible_playbook_python}}"
