---
- name: Install host requisites
  dnf:
      name: btrfs-progs,arch-install-scripts,systemd-container,python3-libselinux
      state: latest

- name: Create individual containers
  include_tasks: bootstrap_arch_container.yml
  with_items: "{{ containers }}"
  loop_control:
    loop_var: container

- name: Cleanup bootstrap image
  file:
      path: /tmp/arch-bootstrap.tar.xz
      state: absent

